pipeline{
    agent any
    stages {
        stage('Fluffy Build'){
            steps{
                echo 'Place Holder'
                sh 'echo Edited Place Holder'
            }
        }

        stage('Fluffy Test'){
            steps{
                sh 'sleep 5'
                sh 'echo success!'
            }
        }

        stage('Fluffy Deploy'){
            steps{
                echo 'Place Holder'
            }
        }
    }
}
